import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

// Wir nutzen import.meta.dirname um den Pfad zum Skript-Ordner zu finden
const root = resolve(import.meta.dirname, '..');
const outputPath = resolve(root, 'src/app/spa/[variants]/[[...path]]/spaHtmlTemplates.ts');

// Das hier ist das "Skelett", das Lobe Chat braucht, um im Browser zu starten.
// Das <div id="root"></div> ist der Ankerpunkt für das gesamte Interface.
const fakeHtml = '<html><head><meta charset="utf-8"/></head><body><div id="root"></div></body></html>';

const output = `// Auto-generated by scripts/generateSpaTemplates.mts for Vercel stability
export const desktopHtmlTemplate = ${JSON.stringify(fakeHtml)};
export const mobileHtmlTemplate = ${JSON.stringify(fakeHtml)};
`;

writeFileSync(outputPath, output, 'utf8');
console.log("Vercel-Fix: spaHtmlTemplates.ts wurde erfolgreich mit Dummy-Werten erstellt.");
